# Generated by Django 5.1.4 on 2025-01-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0011_remove_audit_accessibility_statement_backup_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="retestcheckresult",
            name="id_within_case",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="reteststatementcheckresult",
            name="id_within_case",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="statementcheckresult",
            name="id_within_case",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
