# Generated by Django 5.1.4 on 2025-01-21 08:48

from django.db import migrations


def populate_id_within_case(apps, schema_editor):  # pylint: disable=unused-argument
    Audit = apps.get_model("audits", "Audit")
    StatementCheckResult = apps.get_model("audits", "StatementCheckResult")
    Retest = apps.get_model("audits", "Retest")
    RetestCheckResult = apps.get_model("audits", "RetestCheckResult")
    RetestStatementCheckResult = apps.get_model("audits", "RetestStatementCheckResult")
    for audit in Audit.objects.all():
        id_within_case = 0
        for statement_check_result in StatementCheckResult.objects.filter(audit=audit):
            id_within_case += 1
            statement_check_result.id_within_case = id_within_case
            statement_check_result.save()

    for retest in Retest.objects.all():
        for retest_check_result in RetestCheckResult.objects.filter(retest=retest):
            retest_check_result.id_within_case = (
                retest_check_result.check_result.id_within_case
            )
            retest_check_result.save()

        id_within_case = 0
        for retest_statement_check_result in RetestStatementCheckResult.objects.filter(
            retest=retest
        ):
            id_within_case += 1
            retest_statement_check_result.id_within_case = id_within_case
            retest_statement_check_result.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0012_retestcheckresult_id_within_case_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_id_within_case, reverse_code=reverse_code),
    ]
